### ISSUE TITLE
ERROR [1474483153. 776551266] : Failed SetMode

### ISSUE THREAD

**Issue by TonderaiZR** [erlerobot/ros_erle_takeoff_land#2]
Hello

After running 

rosrun ros_erle_takeoff_land ros_erle_takeoff_land

This error aappears.

ERROR [1474483153. 776551266] : Failed SetMode

Hope you can help

**Comment by imuguruza** [comment]
Have you checked the parameter `ARMING_CHECK` si set to `0`?

**Comment by TonderaiZR** [comment]
Hello 

ARMING_CHECK is set to 0.  

Kind regards..

Tondy

**Comment by ahcorde** [comment]
First at all, are you able to change the mode of your vehicle with a Ground control Station?

What is the value of SYSID_MYGCS? Must be `1`

Generally we answer these questions in [Erle Robotics Forum](http://forum.erlerobotics.com/)

**Comment by vmayoral** [comment]
The right place for requesting support is the forum as @ahcorde pointed out.
Closing this.
