### ISSUE TITLE
Multiple Erle-Copters 

### ISSUE THREAD

**Issue by AliSiddiqui4** [erlerobot/ros_erle_takeoff_land#3]
Hi,

I managed to spawn 3 erle-copters in Gazebo by modifying the erle-copter spawn launch file. But as there is only 1 MAVlink so once I try hovering the quads all three of them go hay wire and ust fly away randomly.

How to make separate MAV for each robots or any other alternatives?

**Comment by vmayoral** [comment]
@AliSiddiqui4 please bring this to our [support forum](http://forum.erlerobotics.com/).
