### ISSUE TITLE
Error occurred when I'm launching the ros_erle_takeoff_land package 

### ISSUE THREAD

**Issue by david-spc** [erlerobot/ros_erle_takeoff_land#5]
Hello, I followed the guide in http://docs.erlerobotics.com/simulation/configuring_your_environment, then I tried to test it and launch the ros_erle_takeoff_land package downloaded from here. Unfortunately, the error occurred as bellow:
![tim 20170913213507](https://user-images.githubusercontent.com/31400511/30419432-da9d9a34-9968-11e7-977d-b932353d9ff4.png)

Because of the success of configuring my environment, I have no idea about why this happened. So, I turn to you. Thanks

**Comment by imuguruza** [comment]
@david-spc I suggest you to ask in the [forum](http://forum.erlerobotics.com/).

Regards
